version: '3.4'
services:
  influxdb:
    image: influxdb:2.7.11-alpine
    restart: unless-stopped
    ports:
      - 8086:8086
    env_file:
        - ~/.influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2

  telegraf:
    depends_on:
      - influxdb
    build:
      context: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /root/.ssh/config:/etc/ssh/ssh_config.d/devana.conf:ro
      - /root/.ssh:/etc/telegraf/.ssh
    env_file:
      - ~/.influxdb
    restart: unless-stopped
    
  app:
    depends_on:
      - influxdb
    build:
      context: app
    restart: unless-stopped
    ports:
      - 8085:80
