version: '3.4'
services:
  influxdb:
    image: influxdb:2.7.11-alpine
    restart: unless-stopped
    ports:
      - 8086:8086
    env_file:
        - ~/.influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2

  telegraf:
    image: telegraf:1.34.0-alpine
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - ~/.influxdb
    
  devana-leaderboard:
    depends_on:
      - influxdb
    build:
      context: devana-leaderboard
    restart: unless-stopped
    ports:
      - 8085:80